config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations: 'users/registrations'
  }
  
  resources :stories

  get '@:username/story_id' , to: 'index#show' , as: 'story_index'
  get '@:username' , to: 'index#user' , as: 'user_index'

  root 'index#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_choice, use: :slugged
  include AASM
  belongs_to :user
  validates :title, presence: true

  default_scope { where(deleted_at: nil)}

  def destroy
    update(deleted_at: Time.now)
  end

  
  aasm(column: 'status', no_direct_assignment: true) do
    state :draft, initial: true
    state :published

    event :publish do
      transitions from: :draft, to: :published
    end

    event :unpublish do
      transitions from: :published, to: :draft
    end

  end
  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end

  private


  def slug_choice
    [
    :title,
    [:title, SecureRandom.hex[0,6]]
    ]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stories
  validates :username, presence: true, uniqueness: true
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

    private
    def record_not_found
        render file: "#{Rails.root}/public/404.html",
              status: :not_found,
              layout: false
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

    def index
        @stories = Story.order(created_at: :desc).includes(:user)
    end
    
    def show

    end


    def user

    end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_story, only: [:edit, :update, :destroy]

    def new
        @story = current_user.stories.new
    end

    def index
        @stories = current_user.stories.order(created_at: :desc)
    end

    def edit

    end

    def update
        if @story.update(story_params)
            case
              when params[:publish]
                @story.publish!
                redirect_to stories_path, notice: '更新成功，已發佈'
              when params[:unpublish]
                @story.unpublish!
                redirect_to stories_path, notice: '儲存至草稿'
              else
                redirect_to stories_path, notice: '更新儲存'
            end

        else
            render :edit
        end
    end

    def create
        @story = current_user.stories.new(story_params)

        @story.status = 'published' if params[:publish]    

        if @story.save
            if params[:publish]
              redirect_to stories_path, notice: "故事發布成功"
            else
              redirect_to edit_story_path(@story), notice: '故事存入草稿中'
            end
        else
            render :new
        end
    end

    def destroy
        @story.destroy
        redirect_to stories_path, notice:"故事已刪除"
    end

    private
    def story_params
        params.require(:story).permit(:title, :content)
    end
    def find_story
        @story = current_user.stories.friendly.find(params[:id])
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:username, :intro, :avatar])
   end

   def update_resource(resource, params)
     resource.update_without_password(params)
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/index/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css" />
  
    <h1 class="title"> 向 Medium 致敬 </h1>
</head>
<body>
  <section class="columns">
    <!-- left -->
    <section class="column">
      <article>
        <figure class="image">
          <img src="https://fakeimg.pl/350x150/f0f0f0" alt="">
        </figure>
        <h2 class="title is-5">Creating a Pipeline to True Workplace Diversity</h2>
        <p class="content">Providing resources, offering acceptance, and involving people of color are keys to making your company more diverse...</p>
        <footer>
          <p>Arielle Wiltz in Modus</p>
          <p>Aug 7</p>
        </footer>
      </article>
    </section>
    <!-- left -->
    <!-- middle -->
    <section class="column">
      <article class="media">
        <figure class="media-left">
          <img src="https://fakeimg.pl/100x100/">
        </figure>
        <div class="media-content">
          <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
          <footer>
            <p>Arielle Wiltz in Modus</p>
            <p>Aug 7</p>
          </footer>
        </div>
      </article>
      <article class="media">
        <figure class="media-left">
          <img src="https://fakeimg.pl/100x100/">
        </figure>
        <div class="media-content">
          <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
          <footer>
            <p>Arielle Wiltz in Modus</p>
            <p>Aug 7</p>
          </footer>
        </div>
      </article>
      <article class="media">
        <figure class="media-left">
          <img src="https://fakeimg.pl/100x100/">
        </figure>
        <div class="media-content">
          <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
          <footer>
            <p>Arielle Wiltz in Modus</p>
            <p>Aug 7</p>
          </footer>
        </div>
      </article>
    </section>
    <!-- middle -->
    <!-- right -->
    <section class="column">
      <article>
        <figure class="image">
          <img src="https://fakeimg.pl/350x200/f0f0f0" alt="">
        </figure>
        <h2 class="title is-5">Creating a Pipeline to True Workplace Diversity</h2>
        <p class="content">Providing resources, offering acceptance, and involving people of color are keys to making your company more diverse...</p>
        <footer>
          <p>Arielle Wiltz in Modus</p>
          <p>Aug 7</p>
        </footer>
      </article>
    </section>
    <!-- right -->
  </section>

  <hr>

  <section class="columns">
    <!-- article list -->
    <section class="column is-two-thirds">
      <% @stories.each do |story| %>
      <article class="media">
        <div class="media-content">
          <h2 class="title is-4"><%= link_to story.title, story_index_path(story.user.username , story), class: "has-text-grey-darker" , method: 'get' %> </h2>
          <p class="content"><%= story.content %></p>
          <footer>
            <p><%= link_to story.user.username , user_index_path(story.user.username) , class:"button is-primary" %> &nbsp; 
              <%= time_ago_in_words(story.created_at)  %></p>
          </footer>
        </div>
        <figure class="media-right">
          <img src="https://fakeimg.pl/150x150/">
        </figure>
      </article>
      <% end %>
    
    </section>
    <!-- article list -->

    <section class="column">
      <h2 class="title is-4">Popular on Medium</h2>
      <hr>

      <article class="media">
        <div class="media-left">01</div>
        <div class="media-content">
          <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
          <footer>
            <p>Thomas Oppong</p>
          </footer>
        </div>
      </article>

      <article class="media">
        <div class="media-left">02</div>
        <div class="media-content">
          <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
          <footer>
            <p>Thomas Oppong</p>
          </footer>
        </div>
      </article>

      <article class="media">
        <div class="media-left">03</div>
        <div class="media-content">
          <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
          <footer>
            <p>Thomas Oppong</p>
          </footer>
        </div>
      </article>

      <article class="media">
        <div class="media-left">04</div>
        <div class="media-content">
          <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
          <footer>
            <p>Thomas Oppong</p>
          </footer>
        </div>
      </article>

      <article class="media">
        <div class="media-left">05</div>
        <div class="media-content">
          <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
          <footer>
            <p>Thomas Oppong</p>
          </footer>
        </div>
      </article>
    </section>
  </section>
</div>
</section>
</body>
</html>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyMedium</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flash' if notice %>
    <div class="container">

      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_flash.html.erb
<div class="notification is-info">
  <%= notice %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <%= link_to root_path , class:"navbar-item" do %>
        <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
      <% end %>
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        
  
      </div>
  
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% if user_signed_in? %>
              <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                　<%= image_tag current_user.avatar.variant(resize: '50*50') if current_user.avatar.attached? %>
                  <%= current_user.email %>
                </a>
              <div class="navbar-dropdown">
              <%= link_to "會員資料" , edit_user_registration_path , method: 'get', class:"navbar-item" %>
              <hr class="navbar-divider">
              <%= link_to "新增故事" , new_story_path ,  class:"navbar-item" %>
              <%= link_to "故事列表" , stories_path , class:"navbar-item" %>
                                        
                <hr class="navbar-divider">
                  <%= link_to "登出" , destroy_user_session_path , class: "navbar-item" , data: {confirm: "確定登出?"} , method: 'delete' %>
                </div>
            </div>
            </div>
            <% else %>
                
                  <%= link_to "註冊" , new_user_registration_path , class: 'button is-primary' , method: 'get' %>
                  <%= link_to "登入" , new_user_session_path , class: 'button is-light' , method: 'get' %>
                
            <% end %>


          </div>
        </div>
      </div>
    </div>
  </nav>

app/views/stories/_form.html.erb
<% if story.errors.any? %>
    <div class= "notification is-danger">
        <%= story.errors.full_messages.to_sentence %>

    </div>
<% end %>


<%= form_for(story) do |form| %>
    <div class="field">

        <%= form.label :故事標題 , class:'is-size-4 has-text-weight-medium' %>
        <%= form.text_field :title, class: 'input is-warning' %>

    </div>
    <div class="field">

            <%= form.label :故事內文 , class:'is-size-4 has-text-weight-medium' %>
            <%= form.text_area :content, rows:10 , class: 'textarea is-primary is-medium' %>
    
    </div>
    <div class="field">
        <%= form.submit '更新內容' , name: 'save_update', class:'button is-light is-large' %>  &nbsp; &nbsp; &nbsp;
        <%= form.submit '發布故事' , name: 'publish', class:'button is-primary is-large' if story.may_publish?  %>   &nbsp; &nbsp; &nbsp;
        <%= form.submit '存成草稿' , name: 'unpublish' , class: 'button is-warning is-large' if story.may_unpublish? %>
    </div>


<% end %>

app/views/stories/edit.html.erb
<h1 class="is-size-3 has-text-weight-bold has-text-grey-dark">編輯故事</h1>
<%= render 'form', story: @story %>

app/views/stories/index.html.erb
<h1 class="is-size-3 has-text-weight-bold">故事列表</h1><br/>
<hr>
<% @stories.each do |story| %>
  <div class="content">
    <h2 class="is-size-5"> 
      <%= link_to story.title, edit_story_path(story), class: 'has-text-grey' %>
      <%= content_tag :span, '已發佈' , class: 'tag is-warning' if story.published? %>
      <%= content_tag :span, '草稿' , class: 'tag is-light' if story.may_publish? %>

    </h2>
    <p class="is-size-6" ><%= story.content %></p>
    <p class="has-text-weight-light">最後編輯時間:<%= time_ago_in_words(story.updated_at) %>
    <%= link_to "編輯" , edit_story_path(story), class: "button is-text is-small" %>
    <%= link_to "刪除" , story , method: 'delete' ,class: "button is-danger is-small" , data: {confirm: "確認刪除?"} %>
    </p>
    <hr>
  </div>

<% end %>

app/views/stories/new.html.erb
<h1 class="is-size-3 has-text-weight-bold has-text-grey-dark">新增故事</h1>
<%= render 'form', story: @story %>